<!DOCTYPE html>
<html lang="en">

<!-- BEGIN HEAD -->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <title>Otrouha</title>

    <css src="bootstrap/bootstrap.css"/>
    <css src="jquery/jquery-ui.min.css"/>

    <css src="main.css"/>

    {{ \Helpers\Assets::instance()->renderGroup('head') }}
    <!-- END THEME STYLES -->
    <link rel="icon" type="image/png" href="{{ @CDN }}/logo/32,32"/>

</head>
